using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using TradeFlowers.Model;

namespace TradeFlowers.Pages.Dictonary
{
    /// <summary>
    /// Логика взаимодействия для ProductsView.xaml
    /// </summary>
    public partial class ProductsView : UserControl
    {
        public ProductsView()
        {
            InitializeComponent();
            showProduct(0);

        }
        private void dg_AutoGeneratedColumns(object sender, EventArgs e)
        {
            //gridProduct.Columns[0].Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            //gridProduct.Columns[1].Width = new DataGridLength(50, DataGridLengthUnitType.Pixel);
            gridProduct.Columns[0].Header = "Наименование";
            gridProduct.Columns[1].Visibility=Visibility.Hidden;
        }
        public void showProduct(int categoryId)
        {
            using (tradeEntities db = new tradeEntities())
            {
                //var q = db.prod_category.Join(
                //    db.prod_poduct,
                //    c => c.category_id,
                //    p => p.product_category_id,
                //    (c, p) => new
                //    {
                //       Name= p.product_name 
                //    }
                //    );
                var q = db.prod_poduct.
                    Where(x=>x.product_category_id== categoryId).
                    Select(
                    p => new
                    {
                        p.product_name,
                        p.product_id
                    });
                gridProduct.ItemsSource = q.ToList();
                // gridProduct.ItemsSource = db.prod_poduct.ToList();
            }
        }
    }
}
