//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeFlowers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_poduct
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> product_category_id { get; set; }
    
        public virtual prod_category prod_category { get; set; }
    }
}
